blogola/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('posts.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

posts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'posts'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<post_id>[0-9]+)/$', views.post, name='post'),
    url(r'^post/(?P<post_id>[0-9]+)/comment/$', views.comment, name='comment'),
    url(
        r'^comment/(?P<comment_id>[0-9]+)/remove/$',
        views.remove_comment,
        name='remove_comment'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User)
    heading = models.CharField(max_length=256)
    text = models.CharField(max_length=16384)

    class Meta:
        ordering = ['created']


class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    modified = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(
        Post,
        related_name="comments",
        on_delete=models.CASCADE)
    user = models.ForeignKey(User)
    text = models.CharField(max_length=1048)

    class Meta:
        ordering = ['created']

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.exceptions import PermissionDenied
from .models import Post, Comment


def index(request):
    posts = Post.objects.all().order_by('created')

    return render(request, "posts/posts.html", {'posts': posts})


def post(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    return render(request, "posts/post.html", {'post': post})


@login_required
def comment(request, post_id):
    if request.method == "POST" and 'text' in request.POST:
        post = get_object_or_404(Post, id=post_id)

        comment = Comment(
            post=post,
            user=request.user,
            text=request.POST['text'],
        )

        comment.save()

        return JsonResponse(
            {
                'html': render_to_string(
                    "posts/comment.html", {'comment': comment},
                    request=request,
                )
            }
        )

    raise PermissionDenied


@login_required
def remove_comment(request, comment_id):
    if request.method == "POST":
        comment = get_object_or_404(Comment, id=comment_id)
        post_id = comment.post.id

        comment.delete()

        return redirect("posts:post", post_id=post_id)

    raise PermissionDenied

posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Blogola</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          {% if user.is_authenticated %}
            <form class="navbar-form navbar-right" action="{% url 'posts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-success">Sign out ({{request.user.username}})</button>
            </form>
          {% else %}
            <form class="navbar-form navbar-right" action="{% url 'login' %}" method="post">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" name="username" id="id_username" placeholder="Username" class="form-control">
              </div>
              <div class="form-group">
                <input type="password" name="password" id="id_password" placeholder="Password" class="form-control">
              </div>
              <button type="submit" class="btn btn-success">Sign in</button>
            </form>
          {% endif %}
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    {% block content %}
    {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% block js %}
    {% endblock %}
  </body>
</html>

posts/templates/posts/comment.html
<div class="media">
  <span class="glyphicon glyphicon-comment pull-left"></span>
  <div class="media-body">
    <h4 class="media-heading">{{comment.user.username}}
      <small>{{comment.created}}</small>
    </h4>
    {{comment.text}}
  </div>
  <form role="form" action="{% url 'posts:remove_comment' comment_id=comment.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-warning">Remove comment</button>
  </form>
</div>

posts/templates/posts/post.html
{% extends "posts/base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="well">
        <!-- Heading -->
        <h1>{{post.heading}}</h1>

        <!-- Author -->
        <p class="lead">
            by {{post.user.username}}
        </p>

        <!-- Date/Time -->
        <p><span class="glyphicon glyphicon-time"></span> Created on {{post.created}}</p>

      </div>
      <div class="well">

        <!-- Post Content -->
        <p class="lead">{{post.text}}</p>

      </div>

      <!-- Posted Comments -->
      <div id="comments" class="well">
        <h3>Comments</h3>

        <!-- Comment -->
        {% for comment in post.comments.all %}
          <div class="media">
            <span class="glyphicon glyphicon-comment pull-left"></span>
            <div class="media-body">
                <h4 class="media-heading">{{comment.user.username}}
                  <small>{{comment.created}}</small>
                </h4>
                {{comment.text}}
            </div>
            {% if request.user.is_authenticated %}
              <form role="form" action="{% url 'posts:remove_comment' comment_id=comment.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-warning">Remove comment</button>
              </form>
            {% endif %}
          </div>
        {% endfor %}
      </div>

      <!-- Comments Form -->
      <div class="well">
        {% if request.user.is_authenticated %}
          <h4>Leave a Comment:</h4>
          <form id="comment_form" role="form" action="{% url 'posts:comment' post_id=post.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <textarea class="form-control" id="id_text" name="text" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        {% else %}
          <p>Please sign in to add comments</p>
        {% endif %}
      </div>
   </div>
  </div>
{% endblock %}

{% block js %}
<script type="text/javascript">
  $().ready( function() {
    $("#comment_form").submit( function(e) {
      var form = $(this);
      var url = form.attr('action');

      e.preventDefault();

      $.ajax( { 
        async : true,
        url   : url,
        type  : form.attr('method') || "post",
        data  : form.serialize()
      } ) 
      .done( function(response) {
        $('#comments').append( $.parseHTML( response['html'] ) );
      } )
      .fail( function(response) {
        alert( "We were unable to add your comment. Please try again." ); 
      } );

      $('#id_text').val('');
    } );
  } );
</script>
{% endblock %}

posts/templates/posts/posts.html
{% extends "posts/base.html" %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1 class="text-center">Welcome to Blogola!</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    {% for post in posts %}
        <div class="col-md-offset-2 col-md-8">
          <div class="well">
            <!-- Heading -->
            <a href="{% url 'posts:post' post_id=post.id %}">
              <h1>{{post.heading}}</h1>
            </a>

            <!-- Author -->
            <p class="lead">
                by {{post.user.username}}
            </p>

            <!-- Date/Time -->
            <p><span class="glyphicon glyphicon-time"></span> Created on {{post.created}}</p>
          </div>
        </div>
     {% endfor %}
   </div>
  </div>
{% endblock %}